version: '3.1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  app:
    build: .
    command: mix phx.server
    volumes: 
      - ./app:/app
    ports:
      - 8000:4000
    depends_on:
      - db

